name: Deploy to cPanel

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
          path: ${{ github.workspace }}

      - name: Deploy to cPanel
        run: |
          export DEPLOYPATH=/home/adilson/public_html/
          cd $DEPLOYPATH
          dotnet SistemaVeiculos.dll
