name: Build and deploy ASP.Net Core app to cPanel - e2motors

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Deploy to cPanel
        run: |
          - export DEPLOYPATH=/home/adilson/public_html/
          - dotnet publish -c Release -o published-app
          - cp -R published-app/* $DEPLOYPATH
